require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Security/YAMLLoad:
  Exclude:
    - lib/configuration.rb

Style/ClassVars:
  Exclude:
    - lib/configuration.rb

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/**/*

RSpec/NestedGroups:
  Max: 5

RSpec/AnyInstance:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false