defaults: &defaults
  working_directory: ~/weather
  docker:
    - image: cimg/ruby:3.1.2-node
    - image: cimg/base:stable
    - image: cimg/redis:6.2.6
    - image: circleci/postgres:10.4-alpine
      environment:
        POSTGRES_DB: weather_test
        POSTGRES_USER: weather_user
        POSTGRES_PASSWORD: ""
        DATABASE_URL: postgres://weather_user:@127.0.0.1:5432/weather_test

version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@1.4.0
  node: circleci/node@5.0.3
  browser-tools: circleci/browser-tools@1.3.0

commands:
  node_install:
    steps:
      - checkout
      - node/install:
          node-version: '18.12.0'
      - run: node --version
      - run: npm --version
      - node/install-packages

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  bundle_dependencies:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - node_install
  rubocop:
    <<: *defaults
    steps:
      - checkout
      - node_install
      - ruby/install-deps
      - run:
          name: Lint code with rubocop
          command: bundle exec rubocop -D
  rspec:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - node_install
      - ruby/install-deps
      - run:
          name: Database setup
          environment:
            RACK_ENV: test
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
      - run:
          name: RSpec tests
          command: bundle exec rspec spec/
      - store_test_results:
          path: /tmp/test-results

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.1/configuration-reference/#workflows
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
      - rspec:
          requires:
            - bundle_dependencies
